# Generated by Django 5.0.6 on 2024-06-10 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0008_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
