# Generated by Django 5.0.6 on 2024-06-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0010_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite',
            field=models.ManyToManyField(blank=True, to='booking_app.hotel'),
        ),
    ]
